name = "calcefficiency-worker" # Un nombre único para tu Worker
compatibility_date = "2025-06-21" # Fecha de compatibilidad, puedes mantener esta.

# Tu Account ID de Cloudflare
account_id = "38cba2f6562e19b783108f208472d27e"

# Desplegará en tu subdominio workers.dev (ej. calcefficiency-worker.tu-username.workers.dev)
workers_dev = true

# Configuración para Workers Sites, sirviendo tu aplicación React
